### ISSUE TITLE
Include names-, authors- and readers-flags in Domino-Data-Service

### ISSUE THREAD

**Issue by hans-helmut** [OpenNTF/XPagesExtensionLibrary#61]
In Domino names-, authors- and readers-fields are just stored as text-items with the appropriate flags.
The Domino-Data-Service ignores these flags. So after loading (GET) and saving (POST, UPDATE) a document using the Domino-Data-Service, all items containing readers (and having the flag ) are changed to text items. This could cause making confidential documents readable. So I suggest to add the flags at least when GETing a document with the URL-params strongtype=true (or for compatibility with a new param). The same applies to @authors.

Here is an example, actual format:
"myauthors": "CN=Joe Doe/O=IBM"

Suggested format:
"myauthors": {
type: "text",
data: "CN=Joe Doe/O=IBM",
isNames: true,
isAuthors: true,
isReaders: false
}

I am not aware, how much this code is shared with XPages and could cause an incompatibility.

**Comment by paulswithers** [comment]
DQL is a better approach with V10 than DDS. I've never seen DDS used in production and, because of what gets exposed, I would not recommend it. DQL is better performing, will be the REST service access point that gets enhancements and optimisations going forward, and will eventually cover much more. 

There is a lot of cross-over to this idea I posted on Aha, for Document Properties as an API. But becauseof what's exposed, it may be best to restrict access so that it requires higher access than just having access to the document itself, e.g. Designer or above.
