### ISSUE TITLE
Setting a styleClass in a pageTreeNode

### ISSUE THREAD

**Issue by tadrian** [OpenNTF/XPagesExtensionLibrary#8]
I am trying to set the class of a pageTreeNode in the Application layout control but it does not get applied in html 

The following code 

    <xe:this.titleBarTabs>
	<xe:pageTreeNode label="page1" page="/home.xsp" styleClass="teststyle" style="background-color:green"></xe:pageTreeNode>
    </xe:this.titleBarTabs>

Produce the following html (my class 'teststyle' is not added)

    <li style="background-color:green" class="menu-item active"><a href="/db.nsf/home.xsp">page1</a></li>

**Comment by briangleeson** [comment]
@tadrian Could you try this out again? Was just looking at it (with extlib 16 installed) and all custom styles were added as expected. This issue may have been indirectly fixed since it was reported, as it has been sitting in the backlog for quite a while and no specific fix was put in for it to my knowledge.

**Comment by briangleeson** [comment]
I dont think this is an issue any more, happy to be corrected. One point that needed a fix though was in the navigator control, with a fix added in ExtLib release 17
